# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
xcode_scheme: RouterKit
before_install: true
install:
- gem install slather -N
script:
- set -o pipefail
- xctool -scheme 'RouterKit' -sdk iphonesimulator clean test -parallelize
- xctool -scheme 'RouterKit' -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES 
  GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test -parallelize
after_success:
- pod lib lint --quick # ensure podspec is still valid
- slather
