# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
xcode_scheme: RouterKit
before_install: true
script:
- set -o pipefail
- xctool -scheme 'RouterKit' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test -parallelize
after_success:
- pod lib lint --quick # ensure podspec is still valid
- slather
