# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

pod "RouterKit", :path => "../RouterKit.podspec"

target 'RouterKit iOS Example' do

end

target 'RouterKit iOS ExampleTests' do

end

