# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

pod "RouterKit", :path => "../"

target 'RouterKit iOS Example' do

end

target 'RouterKit iOS ExampleTests' do
 pod 'RouterKit', :path => "../"

end

